/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Batman
 */
public class Principal extends javax.swing.JFrame {

    DefaultTableModel modelotabla = new DefaultTableModel();
    List<Atributos> Datos = new ArrayList<>();
    int posicion = 0;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        TitulosTabla();
        Cargar();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtPromedio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtDatos = new javax.swing.JTable();
        btnPro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        checar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Alumnos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        getContentPane().add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, -1));
        getContentPane().add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 180, -1));

        jLabel2.setText("Matricula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel5.setText("Promedio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        tbtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbtDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 638, 223));

        btnPro.setText("Obtener promedio");
        btnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProActionPerformed(evt);
            }
        });
        getContentPane().add(btnPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/Login.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 237, 265));
        getContentPane().add(checar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
           Files conexion = new Files();
           Atributos dato = new Atributos();
           dato.setMatricula(txtMatricula.getText().toString());
           dato.setNombre(txtNombre.getText().toString());
           dato.setCorreo(txtCorreo.getText().toString());
           dato.setPromedio(txtPromedio.getText().toString());
           
           conexion.Agregar(dato);
           Datos = conexion.getDatos();
           if (conexion.Grabar(Datos, 0)){
               modelotabla = (DefaultTableModel) tbtDatos.getModel();
               modelotabla.getDataVector().removeAllElements();
               checar.setText("✔");
               Cargar();
           }else{
               checar.setText("X");
           }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void tbtDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtDatosMouseClicked
        // TODO add your handling code here:
        
        int nfilas = tbtDatos.getSelectedRowCount();
        int fila = 0;
        if(nfilas == 1){
            fila = tbtDatos.getSelectedRow();
            posicion = fila;
            txtMatricula.setText(tbtDatos.getValueAt(fila,0).toString());
            txtNombre.setText(tbtDatos.getValueAt(fila,1).toString());
            txtCorreo.setText(tbtDatos.getValueAt(fila,2).toString());
            txtPromedio.setText(tbtDatos.getValueAt(fila,3).toString());
        }
    }//GEN-LAST:event_tbtDatosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtMatricula.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        txtPromedio.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        Files conexion = new Files();
           Atributos dato = new Atributos();
           dato.setMatricula(txtMatricula.getText().toString());
           dato.setNombre(txtNombre.getText().toString());
           dato.setCorreo(txtCorreo.getText().toString());
           dato.setPromedio(txtPromedio.getText().toString());
           Datos.set(posicion, dato);
           
           if (conexion.Grabar(Datos, 1)){
               modelotabla = (DefaultTableModel) tbtDatos.getModel();
               modelotabla.getDataVector().removeAllElements();
               checar.setText("✔");
               Cargar();
           }else{
               checar.setText("X");
           }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        Files conexion = new Files();
        Datos.remove(posicion);
        if (conexion.Grabar(Datos, 1)){
               modelotabla = (DefaultTableModel) tbtDatos.getModel();
               modelotabla.getDataVector().removeAllElements();
               checar.setText("✔");
               Cargar();
           }else{
               checar.setText("X");
           }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(JOptionPane.showInputDialog("Numero de materias a promediar"));
        double calificacion = 0.0;
        double promedio = 0.0;
        for (int i = 0; i <n; i++) {
            calificacion = Double.parseDouble(JOptionPane.showInputDialog(null,"ingresa la calificacion"));
            promedio +=calificacion;
        }
        double promediofinal = promedio/n;
        String pro = String.valueOf(promediofinal);
        txtPromedio.setText(pro);
    }//GEN-LAST:event_btnProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void Cargar(){
        Files conexion = new Files();
        if(conexion.VerificaArch()){
            if (conexion.Leer()){
                Datos = conexion.getDatos();
                CargarRegistrosTabla();
            }else{
            JOptionPane.showMessageDialog(this,
                        "No se puede leer la informacion",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }else{
            JOptionPane.showMessageDialog(this,"No existe el archivo, ingrese información",
                    "no existe", 
                    JOptionPane.INFORMATION_MESSAGE);   
        }
    }
    
     private void CargarRegistrosTabla(){
         //aqui puede haber error
        Object[] filatabla = new Object[4];
        for(Atributos dato : Datos){
            filatabla[0]=dato.getMatricula();
            filatabla[1]=dato.getNombre();
            filatabla[2]=dato.getCorreo();
            filatabla[3]=dato.getPromedio();
            modelotabla.addRow(filatabla);
        }
        tbtDatos.setModel(modelotabla);
    }
     
     private void TitulosTabla(){
        modelotabla.addColumn("Matricula");
        modelotabla.addColumn("Nombre");
        modelotabla.addColumn("Correo");
        modelotabla.addColumn("Promedio");
        tbtDatos.setModel(modelotabla);
        
    }
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPro;
    private javax.swing.JLabel checar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtDatos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables
}
